version: '3.9'
services:

  basic_environment:
    container_name: basic_env
    build: 
      context: docker/
      dockerfile: ./Dockerfile
      args:
        - CLIENT_ID
        - CLIENT_SECRET
        - GRANT_TYPE
    volumes:
     - ./code:/app
     - ./logs:/logs
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - GRANT_TYPE=${GRANT_TYPE}
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sqldb
      - MYSQL_ROOT_PASSWORD=root

  mongodb:
    image : mongo:latest
    container_name: lufthansa-airLines-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    hostname: mongo-server
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo-db:/data/db

  mySqldb:
    image : mysql:latest
    container_name: lufthansa-airLines-sqldb
    environment:
      - MYSQL_DATABASE=sqldb
      - MYSQL_ROOT_PASSWORD=root
    hostname: mysql-server
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql-db:/var/lib/mysql




     